mkdir -p Subs
cd Subs
touch Prey.2022.1080p.WEBRip.x265-RARBG
touch Prey.2022.1080p.WEBRip.x265-RARBG.mp4
touch RARBG.txt
touch RARBG_DO_NOT_MIRROR.exe
touch 10_Finnish.srt
touch 11_French.srt
touch Subs
touch Latin American.spa.srt
touch SDH.eng.srt
touch dan.srt
touch fin.srt
touch fre.srt
touch ger.srt
touch ita.srt
touch nor.srt
touch por.srt
touch swe.srt
touch 12_Hungarian.srt
touch 13_Italian.srt
touch 14_Japanese.srt
touch 15_Korean.srt
touch 16_Dutch.srt
touch 17_nor.srt
touch 18_Polish.srt
touch 19_Portuguesesrt
touch 19_Portuguese.srt
touch 20_Portuguese.srt
touch 21_Romanian.srt
touch 22_slo.srt
touch 23_Swedish.srt
touch 24_Turkish.srt
touch 25_Chinese.srt
touch 26_Chinese.srt
touch 27_Chinese.srt
touch 2_English.srt
touch 3_English.srt
touch 4_Czech.srt
touch 5_Danish.srt
touch 6_German.srt
touch 7_Greek.srt
touch 8_Spanish.srt
touch 9_Spanish.srt